# --- !Ups

set ignorecase true;

create table "questions" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,
  "name" VARCHAR(254) NOT NULL,
  "description" VARCHAR(1024) NOT NULL
);

create table "parts" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,
  "qId" BIGINT NOT NULL,
  "part" VARCHAR(1024) NOT NULL
  );



create table "answers" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,
  "qId" BIGINT NOT NULL,
  "answer" VARCHAR(1024) NOT NULL
);



# --- !Downs

drop table answers;
drop table part;
drop table responses;

